name: 'interactiondesignfoundation/deployer-action'
description: 'Deploy with Deployer'
inputs:
  private-key:
    description: 'Private key'
    required: true
  known-hosts:
    description: 'Known hosts'
    required: false
    default: ''
  task:
    description: 'Deployer task to run'
    required: true
    default: ''
  path:
    description: 'Path to Deployer, e.g. "./deployer.phar"'
    required: false
    default: ''
  version:
    description: 'Deployer version, e.g. "7.0.0-rc.8"'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: blue
  icon: send
